//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.23 at 06:30:51 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://star.ilgo.zen/star")
package zen.ilgo.star.xml;
